"""Add phone_number to User model

Revision ID: 074c8019c4fa
Revises: aa865f1900c6
Create Date: 2025-07-21 14:52:59.370078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074c8019c4fa'
down_revision = 'aa865f1900c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
