"""add last_notified_at to medication schedule

Revision ID: 45063fa2efe6
Revises: f633c87a2169
Create Date: 2025-07-21 11:47:19.317684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45063fa2efe6'
down_revision = 'f633c87a2169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_notified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_schedule', schema=None) as batch_op:
        batch_op.drop_column('last_notified_at')

    # ### end Alembic commands ###
