"""Remove phone_number and fcm_token from User

Revision ID: 73e361052845
Revises: 074c8019c4fa
Create Date: 2025-07-21 15:04:22.733844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e361052845'
down_revision = '074c8019c4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('fcm_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=25), nullable=True))

    # ### end Alembic commands ###
